### ISSUE TITLE
Patchy results for gene/drug queries

### ISSUE THREAD

**Issue by cbizon** [helxplatform/dug#237]
The use of genes and drugs to get to relevant terms seems a little hit or miss

So in the realm of asthma
"Albuterol" brings back asthma
"ADRB2" does not

For hypertension
"ACE" brings back hypertension
"lisinopril" does not

**Comment by frostyfan109** [comment]
As far as I know, genes/drugs are omitted during annotation (for heal at least). This is also the reason the concept ACE doesn't show up when you search for "ACE".

The reason `albuterol` returns `asthma` and `ace` returns `hypertension` is because there is an exact lexical match within the descriptions of these concepts. For example, for hypertension, near the end of the description you find:
> beta blocker, **ACE** inhibitor, or calcium channel blocker use.

And there is a similar match for "albuterol" somewhere within asthma's description.

<br/>
There likely would be more rigorous underlying connections in Dug between these things, but since drugs/genes aren't annotated, these connections don't get made.
 
I think the reason is that in [roger's annotation config](https://github.com/helxplatform/roger/blob/08e65c71b47b36f651973f84afd29ccc95ea35fb/dags/roger/config/config.yaml#L45), no gene/drug ontologies are greenlisted: 
```yaml
ontology_greenlist: ["PATO", "CHEBI", "MONDO", "UBERON", "HP", "MESH", "UMLS"]
```

**Comment by cbizon** [comment]
Thanks for the cogent explanation @frostyfan109 .  

It is worth noting that CHEBI and MESH/UMLS can contain drugs and MESH/UMLS also contain genes.

I suppose the overall question is whether we think that these types of queries are something we want to enable.

@HowardLander @alexwaldrop I wonder if this is an example of something that would be easier in the identifier-first approach?

**Comment by hhiles** [comment]
@cbizon should this move to jira?

**Comment by cbizon** [comment]
Yes, and it can be made a sub-task of the prototype
