### ISSUE TITLE
A user can create a json file of Dug search results to take outside of Dug for further analyses

### ISSUE THREAD

**Issue by hhiles** [helxplatform/dug#249]
This work satisfies the need for a Dug Shopping Cart. It is broken into 3 buckets for v1.

From the card view, a user can click `studies` and select 1 or more studies to send it to the shopping cart
- [ ] @mbwatson  fill out discreet steps

After expanding the card view and selecting `studies`, a user can expand individual studies and select 1 o more variables to send to the shopping cart
- [ ] @mbwatson fill out discreet steps 

View their shopping cart with a list of all selected items for export to json
- [ ] @mbwatson fill out discreet steps

**Comment by frostyfan109** [comment]
Cart to do list
- [ ] Add CDEs to cart. Do we want them in their own bucket or the study bucket?) 
- [ ] Sticky banner so that users can access cart while scrolled down (very relevant now that infinite scroll is added).
  - [ ] Do we want to have the search bar sticky to the top too? My inclination is yes, this is how other search engines do it.
- [ ] Import shopping cart files
- [ ] Need to fix placeholder text for cart creation popup (involves some changes to the `antd-shopping-cart` package)
![image](https://user-images.githubusercontent.com/31631417/184253358-2a82c5bf-43a6-412f-92d9-59b1f0357c35.png)
- [ ] Should your active cart remain active when you reopen the page?

Add to the far in the future list:
- The UI should indicate whether a user has permissions on a given study/variable (and maybe cdes as well? not sure)

**Comment by gaurav** [comment]
"Search for your cart" placeholder text is very faint.

**Comment by hhiles** [comment]
@gaurav and @frostyfan109 can we please migrate all of this information to Jira? We need to be be tracking our work effort there instead of here.
